# From https://github.com/QuantumObject/docker-zoneminder/issues/49#issuecomment-436931588
version: "3.7"
services:

  db:
    image: "mysql/mysql-server:5.7"
    environment:
      - TZ=America/Los_Angeles
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/cache:/etc/mysql:ro"
    networks:
      - cctv
    restart: on-failure:5

  zm:
    image: quantumobject/docker-zoneminder
    build:
      context: .
      shm_size: '4gb'
    depends_on:
      - db
    environment:
      - TZ=America/Los_Angeles
      - ZM_DB_HOST=db
      - SERVICE_PORTS="8081"
    volumes:
      - /var/empty
      - "./backups:/var/backups"
      - "./cache:/var/cache/zoneminder"
      - type: tmpfs
        target: /dev/shm
    networks:
      - cctv
    ports:
      - "80:80"
    restart: on-failure:5

networks:
  cctv:
    driver: bridge
